export const AssetDisplayData = [
  {
    icon: "/tokens/qAR.svg",
    name: "Quantum Arweave",
    amount: "13,579.24",
    symbol: "qAR",
    apr: "4.57",
    change: "0.02",
    isPositive: true,
    extraAmount: "1",
  },
  {
    icon: "/tokens/DAI.svg",
    name: "Dai",
    amount: "124.5",
    symbol: "DAI",
    apr: "2.03",
    change: "0.17",
    isPositive: false,
    extraAmount: "1",
  },
  {
    icon: "/tokens/stETH.svg",
    name: "Staked Ethereum",
    amount: "13,579.24",
    symbol: "stETH",
    apr: "4.57",
    change: "0.02",
    isPositive: true,
    extraAmount: "1",
  },
  {
    icon: "/tokens/qAR.svg",
    name: "Quantum Arweave",
    amount: "13,579.24",
    symbol: "qAR",
    apr: "4.57",
    change: "0.02",
    isPositive: true,
    extraAmount: "1",
  },
  {
    icon: "/tokens/DAI.svg",
    name: "Dai",
    amount: "124.5",
    symbol: "DAI",
    apr: "2.03",
    change: "0.17",
    isPositive: false,
    extraAmount: "1",
  },
  {
    icon: "/tokens/stETH.svg",
    name: "Staked Ethereum",
    amount: "13,579.24",
    symbol: "stETH",
    apr: "4.57",
    change: "0.02",
    isPositive: true,
    extraAmount: "1",
  },
];

export const marketData = [
  {
    icon: "/tokens/dai.svg",
    name: "Dai",
    symbol: "DAI",
    apy: "4.57",
    utilization: "56.19",
    utilization2: "56.19",
    available: "15.8M",
    availableCurrency: "USD",
    lent: "16.3M",
    lentCurrency: "USD",
  },
  {
    icon: "/tokens/qAR.svg",
    name: "qAR",
    symbol: "qAR",
    apy: "4.57",
    utilization: "56.19",
    utilization2: "56.19",
    available: "15.8M",
    availableCurrency: "USD",
    lent: "16.3M",
    lentCurrency: "USD",
  },
  {
    icon: "/tokens/stETH.svg",
    name: "Staked ETH",
    symbol: "stETH",
    apy: "4.57",
    utilization: "56.19",
    utilization2: "56.19",
    available: "15.8M",
    availableCurrency: "USD",
    lent: "16.3M",
    lentCurrency: "USD",
  },
];
